
srsran_project_dir: /opt/srsRAN_Project
srsran_project_repo: https://github.com/srsran/srsRAN_Project.git
srsran_project_hash: 4ac5300d4927b5199af69e6bc2e55d061fc33652

srsran_project_build_5gc: false

srsran_project_enable_du_e2: false
srsran_project_e2sm_kpm_enabled: false
