
srsran_project_dir: /opt/srsRAN_Project
srsran_project_repo: https://github.com/sadiamimi/srsRAN_Project.git
srsran_project_hash: release_24_10

srsran_project_build_5gc: false

srsran_project_enable_du_e2: false
srsran_project_e2sm_kpm_enabled: false
